name: Bot Pokémon

on:
  schedule:
        - cron: '*/15 * * * *'
   # toutes les 30 minutes
  workflow_dispatch:          # bouton pour lancer à la main

permissions:
  contents: write             # ← autorise le bot à sauvegarder la mémoire

jobs:
  surveiller:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les librairies
        run: pip install requests python-dotenv

      - name: Lancer le bot
        env:
          EBAY_APP_ID: ${{ secrets.EBAY_APP_ID }}
          EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
          EBAY_DEV_ID: ${{ secrets.EBAY_DEV_ID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py

      - name: Sauvegarder la mémoire des alertes
        run: |
          git config user.name "bot-pokemon"
          git config user.email "bot@github.com"
          git add deja_alertees.json
          git commit -m "Mise à jour mémoire alertes" || echo "Rien à sauvegarder"
          git push || echo "Rien à pousser"
